quarkus.http.port=8080

# AWS Configuration
aws.region=${AWS_REGION:us-east-2}
aws.sns.topic-arn=${SNS_TOPIC_ARN:}
aws.sns.endpoint-override=${SNS_ENDPOINT_OVERRIDE:}

# Health & Metrics
quarkus.smallrye-health.root-path=/health
quarkus.micrometer.export.prometheus.path=/metrics

# Logging
quarkus.log.level=INFO
quarkus.log.category."com.feedback".level=DEBUG
